name: Go Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Update dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run main.go
        id: run_main
        run: |
          if go run main.go; then
            echo "Success"
            exit 0
          else
            echo "Err"
            exit 1
          fi
